#!/bin/sh

set -e

action=$1
version=$2

if [ "${DEBCONF_RECONFIGURE}" = "1" ]; then
    action=reconfigure
fi

if [ "x$version" = "x" ] || [ "$action" = "reconfigure" ]; then
#    db_get plexmediaserver/user
#    USER="${RET:-plex}"
    USER="plex"

    if ! getent passwd "$USER" >/dev/null; then
	    adduser --quiet --system --shell /bin/bash --home /var/lib/plexmediaserver --group "$USER"
    fi
fi

#DEBHELPER#

exit 0

